# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  redis:
    image: redis:latest
    command: redis-server #--requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379
   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080